platform :ios, '8.0'

target 'Museum' do
  pod 'AFNetworking', '~> 3.1.0'
  pod 'Masonry'
  pod 'SDWebImage', '~> 4.0'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'IQKeyboardManager'                                 #键盘处理
  pod 'DeviceInfo'                                        #DeviceInfo
  pod 'MBProgressHUD', '~> 0.9.2'                         #提示信息
  pod 'NhfUIColorUnit'                                    #NhfUIColorUnit
  pod 'NhfCacheDeal'                                      #NhfCacheDeal
  pod 'NHFUIImage'                                        #NHFUIImage
  pod 'NHFFontUnit'                                       #NHFFontUnit
  pod 'NHFLabel'
  pod 'NHFNSString'
  pod 'RealReachability'
  pod 'SDCycleScrollView','~> 1.73'
  pod 'CLPlayer'
  pod 'UMengUShare/UI'  # U-Share SDK UI模块（分享面板，建议添加）
  
  # 集成微信(精简版0.2M)
  pod 'UMengUShare/Social/ReducedWeChat'
  
  # 集成QQ/QZone/TIM(精简版0.5M)
  pod 'UMengUShare/Social/ReducedQQ'

  
  # 集成新浪微博(精简版1M)
  pod 'UMengUShare/Social/ReducedSina'
  pod 'NYXImagesKit'
  pod 'ZXingObjC', '~> 3.2.2'
  pod 'mob_smssdk'

end
